name: check variables
on:
  push:
    branches:
      - main
    paths:
      - 'check-variables/**'
  pull_request:
    branches:
      - main
    paths:
      - 'check-variables/**'
  workflow_dispatch:

jobs:
  dump_variables:
    name: Dump variables
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"